server:
  port: 8080

spring:
  cloud:
    gateway:

      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}
            allowedMethods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
            allowedHeaders: ${CORS_ALLOWED_HEADERS:*}

      default-filters:
        - TokenRelay
      routes:
        - id: patients-service
          uri: lb://PATIENTS-SERVICE
          predicates:
            - Path=/api/v1/patients/**

        - id: auth-service-keycloak
          uri: ${AUTH_SERVICE_URI:http://localhost:8081}
          predicates:
              - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/?(?<segment>.*), /realms/medicore-realm/protocol/openid-connect/$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
